name: Build

on:
  push:
    branches: [ main ]
    paths:
    - 'go.mod'
    - 'source/**.go'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      run: mkdir --verbose ./builds/

    - name: Build Project for Linux (x64)
      env:
        GOOS: linux
        GOARCH: amd64
      run: |
        go build -v -ldflags='-s -w' -o ./builds/rcon-$GOOS-$GOARCH ./source/
        strip ./builds/rcon-$GOOS-$GOARCH

    - name: Build Project for Windows (x64)
      env:
        GOOS: windows
        GOARCH: amd64
      run: |
        go build -v -ldflags='-s -w' -o ./builds/rcon-$GOOS-$GOARCH.exe ./source/
        strip ./builds/rcon-$GOOS-$GOARCH.exe

    - name: Upload Builds
      uses: actions/upload-artifact@v3
      with:
        name: builds
        path: ./builds/
